name: nlp_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10,<3.13
  - numpy>=1.18.5,<2.0
  - pandas>=2.2.3,<3.0.0
  - matplotlib>=3.10.1,<4.0.0
  - scikit-learn>=1.6.1,<2.0.0
  - jinja2>=3.1.6,<4.0.0
  - seaborn>=0.13.2,<0.14.0
  - tqdm>=4.67.1,<5.0.0
  - ipykernel>=6.29.5,<7.0.0
  - gensim>=4.3.3,<5.0.0
  - nltk>=3.9.1,<4.0.0
  - ipywidgets>=8.1.7
  - jupyterlab>=4.4.2
  - notebook>=7.4.1
  - pip
  - pip:
      - opencv-python>=4.11.0.86,<5.0.0.0
      - plotly-express>=0.4.1,<0.5.0
      - optuna>=4.2.1,<5.0.0
      - kagglehub>=0.3.12,<0.4.0
      - ultralytics>=8.3.120,<9.0.0
      - fasttext>=0.9.3,<0.10.0
      - torch==2.3.0
      - torchvision==0.18.0
      - torchtext==0.18.0
      - evaluate>=0.4.3,<0.5.0
      - datasets>=3.6.0,<4.0.0
